version: '3'
services:
  dev:
    image: node:11
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "yarn install && yarn start"
    ports:
      - '8000:8000'
      - '3000:3000'
      - '9229:9229'
  db:
    image: postgres:10.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: plum_auth
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_PLUGINS: 'dump-json'
volumes:
  dbdata:
