# best practice: never commit config file to source control
# because it contains sensitive data and each config might be different in other machine

# example : dbUri: "mysql://root:unique123@localhost/cool_db"
dbUri: "mysql://<user>:<password>@<server>/<db>"
# generate jwt secret with random string
jwtSecret: "random string"
